# Generated by Django 6.0.5 on 2026-05-29 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cálculo')),
                ('alpha_utilizado', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Alpha (SES)')),
                ('demanda_pronosticada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Demanda pronosticada')),
                ('punto_reorden', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Punto de reorden (ROP)')),
                ('periodos_calculados', models.PositiveIntegerField(default=3, verbose_name='Períodos calculados')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Predicción de Stock',
                'verbose_name_plural': 'Predicciones de Stock',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Período (mes)')),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad consumida')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Historial de Demanda',
                'verbose_name_plural': 'Historiales de Demanda',
                'ordering': ['producto', 'periodo'],
                'unique_together': {('producto', 'periodo')},
            },
        ),
    ]
