# Generated by Django 6.0.5 on 2026-08-24 19:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alpha',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.3000'), help_text='Parámetro de suavizamiento exponencial simple, entre 0 y 1 (RF013).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('1.0000'))], verbose_name='Alpha (SES)'),
        ),
    ]
