# Generated by Django 6.0.5 on 2026-08-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_alpha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='lead_time_dias',
            field=models.PositiveIntegerField(default=1, help_text='Tiempo de entrega usado para calcular el Punto de Reorden (RF012, RF013).', verbose_name='Tiempo de entrega (días)'),
        ),
    ]
